config/routes.rb
Rails.application.routes.draw do
  root("pages#home")

  get("/projects", to: "pages#projects")
  get("/articles", to: "pages#articles")
  get("/experience", to: "pages#experience")
  get("/aboutme", to: "pages#aboutme")

  get("/create_project", to: "projects#new")
  post("/create_project", to: "projects#create")
  delete("/projects/:id/delete" => "projects#destroy", as: "delete_project")
  get("/projects/:id/delete", to: "projects#destroy")

  get("/create_article", to: "articles#new")
  post("/create_article", to: "articles#create")
  delete("/articles/:id/delete" => "articles#destroy", as: "delete_article")
  get("/articles/:id/delete" => "articles#destroy")

  get("/secret_login", to: "sessions#new")
  post("/secret_login", to: "sessions#create")
  get("/secret_logout", to: "sessions#destroy")
  delete("/secret_logout", to: "sessions#destroy")

  resources(:users)
  resources(:posts)
  resources(:projects)
  resources(:articles)

end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates(:first_name, presence: true)
  validates(:last_name, presence: true)
  validates(:username,
            presence: true,
            uniqueness: true,
            length: { minimum: 6 })
  validates(:email,
            presence: true,
            uniqueness: true,
            format: { with: VALID_EMAIL_REGEX },
            length: { maximum: 255 })
  validates(:password,
            presence: true,
            length: { minimum: 6 })

  has_secure_password

  before_save { !username.downcase; !email.downcase }

  has_one(:role)
  has_one(:permission)
  has_many(:post)

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action(:matches_login_user, only: [:show])

  def show
    @user = User.find(params[:id])
  end

  private

  def matches_login_user
    redirect_to(root_url) unless is_current_user?(current_user())
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% provide(:title, "Profile")%>

<div class="v-container">
  <div class="v-container-item">

    <% if logged_in?() %>
      <h1><%= @user.username %></h1>
    <% end %>

    <% if is_admin?(@user) %>
      <nav class="h-nav", style="margin-bottom: 10px;">
        <ul>
          <% if can_create?(@user) %>
            <li><%= link_to("Create Project", create_project_path) %></li>
            <li><%= link_to("Create Article", create_article_path) %></li>
          <% end %>
        </ul>
      </nav>
    <% end %>

  </div>
</div>