config/routes.rb
Rails.application.routes.draw do
  root("pages#home")

  get("/projects", to: "pages#projects")
  get("/articles", to: "pages#articles")
  get("/experience", to: "pages#experience")
  get("/aboutme", to: "pages#aboutme")

  get("/create_project", to: "projects#new")
  post("/create_project", to: "projects#create")
  delete("/projects/:id/delete" => "projects#destroy", as: "delete_project")
  get("/projects/:id/delete", to: "projects#destroy")

  get("/create_article", to: "articles#new")
  post("/create_article", to: "articles#create")
  delete("/articles/:id/delete" => "articles#destroy", as: "delete_article")
  get("/articles/:id/delete" => "articles#destroy")

  get("/secret_login", to: "sessions#new")
  post("/secret_login", to: "sessions#create")
  get("/secret_logout", to: "sessions#destroy")
  delete("/secret_logout", to: "sessions#destroy")

  resources(:users)
  resources(:posts)
  resources(:projects)
  resources(:articles)

end

app/views/shared/_article_preview.html.erb
<ul class="post-preview-list">
    <% posts.each do |p|%>
        <li class="post-preview-item">
            <a class="post-preview-link" href="<%= article_path(p) %>">
                <h1 class="post-preview-title"><%= p.title %></h1>
                <%= image_tag(p.thumbnail, class: "post-preview-thumbnail") %>
                <small class="post-preview-date"><%= p.created_at.to_formatted_s(:long_ordinal) %> GMT</small>
            </a>
        </li>
    <% end %>
</ul>

<% unless pagy == nil %>
    <%== pagy_nav(pagy).html_safe %>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash.count > 0 %>
  <div class="v-container">
    <% flash.each do |type, msg| %>
      <div class="alert-<%= type %>"><%= msg %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <nav id="footer-nav" class="v-nav">
    <ul>
      <li>
        <a href="https://github.com/Michael-R-R" target="_blank">
          <%= image_tag("icons/github-mark-white.png", alt: "GitHub icon", id: "footer-github-icon") %>
          GitHub
        </a>
      </li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div id="header-title"><strong>Michael's Portfolio</strong></div>
  <div id="header-description">Collective Location of Imaginative Logic</div>

  <nav id="header-nav" class="h-nav">
    <ul>
      <li><%= link_to("Home", root_path) %></li>
      <li><%= link_to("Projects", projects_path) %></li>
      <li><%= link_to("Articles", articles_path) %></li>
      <li><%= link_to("Experience", experience_path) %></li>
      <li><%= link_to("About Me", aboutme_path) %></li>
    </ul>

    <ul>
      <% if logged_in?() %>
        <li><%= link_to("Profile", current_user) %></li>
        <li><%= link_to("Log out", secret_logout_path, data: { "turbo-method": :delete }) %></li>
      <% end %>
    </ul>
  </nav>

  <% unless yield(:header_img_path) == ""%>
    <div id="header-banner-container">
      <div id="header-banner-img-container">
        <%= image_tag(yield(:header_img_path), alt: "Header banner image", id: "header-banner-img") %>
      </div>
    </div>
  <% end %>

</header>

app/views/shared/_post_form.html.erb
<% provide(:title, title) %>

<div class="v-container">
    <div class="v-container-item">
        <%= form_with(url: path, model: post, data: { turbo: false }) do |f| %>
            <%= f.label(:title) %>
            <%= f.text_field(:title) %>

            <%= f.label(:thumbnail) %>
            <%= f.text_field(:thumbnail) %>

            <%= f.label(:content) %>
            <%= f.rich_text_area(:content) %>

            <%= f.submit(submit_text) %>
        <% end %>
    </div>
</div>

app/views/shared/_post_preview.html.erb
<ul class="post-preview-list">
    <% posts.each do |p|%>
        <li class="post-preview-item">
            <a class="post-preview-link" href="<%= post_path(p) %>">
                <h1 class="post-preview-title"><%= p.title %></h1>
                <%= image_tag(p.thumbnail, class: "post-preview-thumbnail") %>
                <small class="post-preview-date"><%= p.created_at.to_formatted_s(:long_ordinal) %> GMT</small>
                <div class="post-preview-body"><%== p.body.html_safe %></div>
            </a>
        </li>
    <% end %>
</ul>

<% unless pagy == nil %>
    <%== pagy_nav(pagy).html_safe %>
<% end %>

app/views/shared/_project_preview.html.erb
<ul class="post-preview-list">
    <% posts.each do |p|%>
        <li class="post-preview-item">
            <a class="post-preview-link" href="<%= project_path(p) %>">
                <h1 class="post-preview-title"><%= p.title %></h1>
                <%= image_tag(p.thumbnail, class: "post-preview-thumbnail") %>
                <small class="post-preview-date"><%= p.created_at.to_formatted_s(:long_ordinal) %> GMT</small>
            </a>
        </li>
    <% end %>
</ul>

<% unless pagy == nil %>
    <%== pagy_nav(pagy).html_safe %>
<% end %>

app/views/shared/_show_post.html.erb
<% content_for(:head) do %>
  <%= stylesheet_link_tag("public/show_post", "data-turbo-track": "reload") %>
<% end %>

<div class="v-container">
  <div class="v-container-item">

    <% if is_admin?(current_user()) %>
      <nav class="h-nav", style="margin-top:10px;">
        <ul>
          <% if can_edit?(current_user()) %>
            <li><%= link_to("Edit", edit_path) %></li>
          <% end %>

          <% if can_delete?(current_user()) %>
            <li><%= link_to("Delete", delete_path, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }) %></li>
          <% end %>
        </ul>
      </nav>
    <% end %>

    <h1 class="post-title"><%= post.title %></h1>
    <small class="post-date">Created - <%= post.created_at.to_formatted_s(:long_ordinal) %> GMT</small>
    <% unless post.created_at == post.updated_at %>
      <small class="post-date">Edited - <%= post.updated_at.to_formatted_s(:long_ordinal) %> GMT</small>
    <% end %>
    <%= image_tag(post.thumbnail, class: "post-thumbnail") %>
    <div class="post-body"><%= post.content %></div>

  </div>
</div>